// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qihnudawjzcipzyebhxs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpaG51ZGF3anpjaXB6eWViaHhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxNDMxMzksImV4cCI6MjA2NDcxOTEzOX0.ZyU2L-skNW-P_YapMaeHOgDYeGefVSRj7gxBbWp5rHU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);